[package]
name = "mdbook-qr"
version = "1.0.0"
edition = "2024"
authors = ["Seb Blair <s.blair@gre.ac.uk>"]
description = "An mdBook preprocessor that generates a QR code using fast_qr."
license = "MIT"
repository = "https://github.com/CompEng0001/mdbook-qr"
documentation = "https://docs.rs/mdbook-qr"
readme = "README.md"
keywords = ["mdbook", "preprocessor", "qr", "fast-qr"]
categories = ["text-processing", "web-programming"]

[lib]
name = "mdbook_qr"
path = "src/lib.rs"

[[bin]]
name = "mdbook-qr"
path = "src/main.rs"

[dependencies]
mdbook-preprocessor = "0.5.2-beta.2"
clap = "4.5.54"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
toml = "0.9.8"
anyhow = "1"
pathdiff = "0.2"
fast_qr = { version = "0.13.1", features = ["image"] }
env_logger = "0.11"
log = "0.4.29"
blake3 = "1.8.3"
semver = "1"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
